#!/bin/bash

# Mx70 Tools V.0.1
# code by Mx70liT
# gausah ganti copyright kalo mau di hargai :)
clear

blue='\e[0;34'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

###################################################
# CTRL C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "
sleep 1
echo ""
echo -e $green"[#]> Thankss"
sleep 1
echo ""
echo -e $white"[#]> sampai jumpa "
read enter
exit
}

echo -e $red"      ____     ____ ___    ___  ________  ________"
echo -e $red"     /    \   /    \\  \  /  / |_____   ||  ____  |"
echo -e $red"     |     \_/     | \  \/  /       /  / | |    | |"
echo -e $white"     |   |\   /|   | /      \      /  /  | |____| |"
echo -e $white"     |___| \_/ |___|/___/\___\    /__/   |________|"
echo -e $green"     ***********************************************"
echo -e $cyan"     #         $red    Tools For Hack               $cyan   #"
echo -e $green"     # $white Coded     : Mx70lit                      $green   #"
echo -e $cyan"     # $red IG        : Medhat_70lit                 $cyan   #"
echo -e $green"     # $white greetz    : DarkmythsCyberTeam         $green     #"
echo -e $cyan"     # $red copyright : Mx70liT © 2018             $cyan     #"
echo -e $green"     # $white thanks to : All Member DMCT            $green     #"
echo -e $cyan"     ***********************************************"
echo " "
echo -e $red" 01) Spam Whatsapp"
echo -e $white" 02) Multi BruteForce"
echo -e $red" 03) Webdav"
echo -e $white" 04) Metasploit"
echo -e $red" 05) BruteForce Instagram"
echo -e $white" 06) phising"
echo -e $red" 07) Kali Nethunter"
echo -e $white" 08) Ubuntu"
echo -e $red" 09) Youtube Dl"
echo -e $white" 10) viSQL "

echo -e $white""
read -p "[mx70lit]> " act;

if [ $act = 01 ] || [ $act = 01 ]
then
clear
echo -e $green" Installing Spam Whatsapp "
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Mx70lit/spam
echo -e $yellow" selesai cukk"
echo -e $yellow" ketik 'sh spam
sh' untuk melanjutkan "
fi


if [ $act = 02 ] || [ $act = 02 ]
then
clear
echo -e $green" Installing Multi BruteForce "
sleep 1
apt update && apt upgrade
apt install python2
apt install php
apt install git
git clone https://github.com/YukersCreew/mbf
echo -e $yellow" selesai cukk"
echo -e $yellow" ketik 'python2 MBF.py' untuk melanjutkan "
fi

if [ $act = 03 ] || [ $act = 03 ]
then
clear
echo -e $green" Installing Multi BruteForce "
sleep 1
apt update && apt upgrade
apt install python2
apt install php
cd Webdav.py
echo -e $yellow" selesai cukk"
echo -e $yellow" ketik 'python2 MBF.py' untuk melanjutkan "
fi

if [ $act = 04 ] || [ $act = 04 ]
then
clear
echo -e $green" Installing Metasploit "
sleep 1
apt update && apt upgrade
apt install git
apt install wget
wget https://raw.githubusercontent.com/verluchie/termux-metasploit/master/install.sh
chmod 777 install.sh
sh install.sh
echo -e $red" selesai Cuk "
fi


if [ $act = 05 ] || [ $act = 05 ]
then
clear
echo -e $green" Installing BruteForce Instagram "
sleep 1
apt update && apt upgrade
apt install python -y
apt install git -y
git clone https://github.com/avramit/instahack/ ighack/
cd ighack
pip install argparse requests PySocks asyncio proxybroker
mv hackinsta.py main.py
echo -e $yellow" selesai cukk"
fi

if [ $act = 06 ] || [ $act = 06 ]
then
clear
echo -e $green" Installing phising "
sleep 1
apt update && apt upgrade
apt install curl
apt install git
git clone https://github.com/thelinuxchoice/shellphish
cd shellpish
bash shellpish.sh
echo -e $yellow" selesai cukk"
fi

if [ $act = 07 ] || [ $act = 07 ]
then
clear
echo -e $green" Installing Kali Nethunter "
sleep 1
apt update && apt upgrade
apt install git
git clone https://github.com/Hax4us/Nethunter-In-Termux.git
cd ~/Nethunter-In-Termux
chmod 777 kalinethunter
sh kalinethunter
echo -e $red" selesai Cuk "
fi


if [ $act = 08 ] || [ $act = 08 ]
then
clear
echo -e $green" Installing Ubuntu "
sleep 1
apt update && apt upgrade
apt install git
apt install wget
apt install proot
git clone https://github.com/Neo-Oli/termux-ubuntu.git
cd ~/termux-ubuntu
chmod +x ubuntu.sh
sh ubuntu.sh
echo " Fix network please wait "
sleep 1
echo "nameserver 8.8.8.8" > /data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs/etc/resolv.conf
echo -e $red" selesai Cuk "
fi


if [ $act = 09 ] || [ $act = 09 ]
then
clear
echo -e $green" Installing Youtube DL "
sleep 1
apt update && apt upgrade
apt install python
pip3 install mps_youtube
pip3 install youtube_dl
apt install mpv
echo " Untuk menjalankannya ketik "mpsyt" tanpa tanda petik "
echo -e $red" selesai Cuk "
fi

if [ $act = 10 ] || [ $act = 10 ]
then
clear
echo -e $green" Installing viSQL "
sleep 1
apt update && apt upgrade
pkg install git
pkg install python
git clone https://github.com/blackvkng/viSQL.git
cd ~/viSQL
chmod 777 viSQL.py
cd ~/
echo -e $red" selesai Cuk "
fi
